#!/usr/bin/env bash

# exercism shortcut
hash exercism 2>&1 && alias exercism='. ~/dev/py/exism/exism.sh exercism'

# bitwig-studio
hash bitwig-studio 2>&1 && alias bitwig-studio='pasuspender bitwig-studio'

# tracktion
hash Tracktion7 2>&1 && alias Trackion7='pasusupender Tracktion7'

# sunvox
hash sunvox 2>&1 && alias sunvox='pasuspender sunvox'
