#!/usr/bin/env bash

# exercism shortcut
hash exercism 2>/dev/null && alias exercism='. ~/dev/py/exism/exism.sh exercism'

# bitwig-studio
hash bitwig-studio 2>/dev/null && alias bitwig-studio='pasuspender bitwig-studio'

# tracktion
hash Tracktion7 2>/dev/null && alias Trackion7='pasusupender Tracktion7'

# sunvox
hash sunvox 2>/dev/null && alias sunvox='pasuspender sunvox'

# Exa
if $(hash exa 2>/dev/null)
then
    alias l="exa"
    alias ll="exa --git -l"
    alias lll="exa --tree"
fi
