#!/usr/bin/env bash

# exercism shortcut
alias exercism='. ~/dev/py/exism/exism.sh exercism'

# bitwig-studio
alias bitwig-studio='pasuspender bitwig-studio'

# tracktion
alias Trackion7='pasusupender Tracktion7'

# sunvox
#alias sunvox='pasuspender sunvox'
