" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

" GIT
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Feature
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' } " fuzzy search
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-surround' " quoting/parenthesis
Plug 'ajh17/vimcompletesme' " autocomplete
Plug 'w0rp/ale' " linter
Plug 'ludovicchabant/vim-gutentags'

" UI
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'morhetz/gruvbox'

" PHP
Plug 'stanangeloff/php.vim'
Plug 'shawncplus/phpcomplete.vim'

" Initialize plugin system
call plug#end()

" UI settings
set nu
set updatetime=100
set mouse=a
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set hls is " hilight search

" Plugins settings
let g:ale_sign_column_always = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = { 'php': ['trim_whitespace'] } 
let g:ale_php_phpcs_standard = 'PSR2'
let g:gutentags_cache_dir = '~/.vim/gutentags'
let g:gutentags_exclude = ['*.css', '*.html', '*.js', '*.json', '*.xml',
                            \ '*.phar', '*.ini', '*.rst', '*.md',
                            \ '*vendor/*/test*', '*vendor/*/Test*',
                            \ '*vendor/*/fixture*', '*vendor/*/Fixture*',
                            \ '*var/cache*', '*var/log*']

" Theme
colo gruvbox
set bg=dark
hi Normal ctermbg=none

" Shortcuts
nmap <C-P> :Files <CR>
